### ISSUE TITLE
ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 12 and the array at index 1 has size 1

### ISSUE THREAD

**Issue by saraemp** [sebhaan/DoEgen#2]
when I ran
$ python -m doegen.doegen test/settings_design_test.yaml

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 12 and the array at index 1 has size 1

Please find below the complete output. Thanks for your help!

$ python -m doegen.doegen test/settings_design_test.yaml
using settings in: 'test/settings_design_test.yaml'
Number of total combinations (Full Factorial): 2916
Perfect time for a cup of tea.
Total estimated runtime:  3.33minutes
--------------------------------
Optimizing array for 12 runs ...
Niteration: 6812
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/smoron/DoEgen/doegen/doegen.py", line 1013, in <module>
    main_cli()
  File "/Users/smoron/DoEgen/doegen/doegen.py", line 1009, in main_cli
    main(**cfg)
  File "/Users/smoron/DoEgen/doegen/doegen.py", line 841, in main
    setup, int(irun), runtime=maxtime_per_run, outpath_nrun=outpath_nrun
  File "/Users/smoron/DoEgen/doegen/doegen.py", line 517, in optimize_design
    effs = evaluate_design2(setup, np.asarray(designs[i]), printopt=False)
  File "/Users/smoron/DoEgen/doegen/doegen.py", line 298, in evaluate_design2
    Acor_can[i, j] = np.corrcoef(Xnorm_c1[:, 0], Xnorm_c2)[0, 1]
  File "<__array_function__ internals>", line 6, in corrcoef
  File "/usr/local/anaconda3/lib/python3.7/site-packages/numpy/lib/function_base.py", line 2551, in corrcoef
    c = cov(x, y, rowvar)
  File "<__array_function__ internals>", line 6, in cov
  File "/usr/local/anaconda3/lib/python3.7/site-packages/numpy/lib/function_base.py", line 2415, in cov
    X = np.concatenate((X, y), axis=0)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 12 and the array at index 1 has size 1

**Comment by sebhaan** [comment]
Thanks. This is likely due to an update in numpy. I've just updated doegen.py with a preliminary patch and should now run without error (still warnings and canonical correlation needs some future update).

**Comment by sebhaan** [comment]
This is now fixed
